spring:
  application:
    name: HibernatePractice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sample
    username: ramyak
    password: Admin@123
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      format-sql: true
      highlight-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format-sql: true
server:
  port: 8000